// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultiasset, StoryblokMultilink } from '../storyblok.d.ts';
export interface FaqItemStoryblok {
  question?: string;
  answer?: StoryblokRichtext;
  component: "faq_item";
  _uid: string;
  _editable?: string | undefined;
}

export interface FaqSectionStoryblok {
  headline?: string;
  items?: FaqItemStoryblok[];
  component: "faq_section";
  _uid: string;
  _editable?: string | undefined;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  _editable?: string | undefined;
}

export interface FootnoteStoryblok {
  label?: string;
  text?: StoryblokRichtext;
  component: "footnote";
  _uid: string;
  _editable?: string | undefined;
}

export interface GallerySectionStoryblok {
  headline?: string;
  images?: StoryblokMultiasset;
  component: "gallery_section";
  _uid: string;
  _editable?: string | undefined;
}

export interface GridStoryblok {
  columns?: (
    | FaqItemStoryblok
    | FaqSectionStoryblok
    | FeatureStoryblok
    | FootnoteStoryblok
    | GallerySectionStoryblok
    | GridStoryblok
    | PageStoryblok
    | RedirectStoryblok
    | RedirectsStoryblok
    | TeaserStoryblok
    | TextSectionStoryblok
  )[];
  component: "grid";
  _uid: string;
  _editable?: string | undefined;
}

export interface PageStoryblok {
  body?: (TextSectionStoryblok | FaqSectionStoryblok | GallerySectionStoryblok)[];
  seo?: {
    _uid?: string;
    plugin?: string;
    title?: string;
    description?: string;
  };
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface RedirectStoryblok {
  source?: string;
  destination?: string;
  permanent?: boolean;
  component: "redirect";
  _uid: string;
  _editable?: string | undefined;
}

export interface RedirectsStoryblok {
  entries?: RedirectStoryblok[];
  component: "redirects";
  _uid: string;
  _editable?: string | undefined;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  _editable?: string | undefined;
}

export interface TextSectionStoryblok {
  eyebrow?: string;
  headline?: string;
  level?: "" | "h2" | "h3";
  lead?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "text_section";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = PageStoryblok | RedirectsStoryblok;
