// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultilink } from '../storyblok.d.ts';
export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  _editable?: string | undefined;
}

export interface GridStoryblok {
  columns?: (
    | FeatureStoryblok
    | GridStoryblok
    | PageStoryblok
    | RedirectStoryblok
    | RedirectsStoryblok
    | TeaserStoryblok
    | TextSectionStoryblok
  )[];
  component: "grid";
  _uid: string;
  _editable?: string | undefined;
}

export interface PageStoryblok {
  body?: TextSectionStoryblok[];
  seo?: {
    _uid?: string;
    plugin?: string;
    title?: string;
    description?: string;
  };
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface RedirectStoryblok {
  source?: string;
  destination?: string;
  permanent?: boolean;
  component: "redirect";
  _uid: string;
  _editable?: string | undefined;
}

export interface RedirectsStoryblok {
  entries?: RedirectStoryblok[];
  component: "redirects";
  _uid: string;
  _editable?: string | undefined;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  _editable?: string | undefined;
}

export interface TextSectionStoryblok {
  eyebrow?: string;
  headline?: string;
  lead?: StoryblokRichtext;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "text_section";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = PageStoryblok | RedirectsStoryblok;
