// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultilink } from '../storyblok.d.ts';
export interface FeatureStoryblok {
  headline?: string;
  text?: StoryblokRichtext;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface GridStoryblok {
  columns?: FeatureStoryblok[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface PageStoryblok {
  body?: (GridStoryblok | TeaserStoryblok)[];
  seo?: {
    _uid?: string;
    plugin?: string;
    title?: string;
    description?: string;
    og_title?: string;
    og_description?: string;
    og_image?: string;
    twitter_title?: string;
    twitter_description?: string;
    twitter_image?: string;
    [k: string]: unknown;
  };
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface TeaserStoryblok {
  headline?: string;
  lead?: string;
  button_label: string;
  button_link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = PageStoryblok;
